# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "861cef9ff25f08fdc3af0cbb47ad9331"
name = "test-cli"
handle = "test-cli-61"
application_url = "https://affecting-gibraltar-allow-glasses.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://affecting-gibraltar-allow-glasses.trycloudflare.com/auth/callback",
  "https://affecting-gibraltar-allow-glasses.trycloudflare.com/auth/shopify/callback",
  "https://affecting-gibraltar-allow-glasses.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
