# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "921edab345e720e6fd604f3642025ac7"
name = "Admin-API"
handle = "admin-api-31"
application_url = "https://blocked-makers-nathan-croatia.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://blocked-makers-nathan-croatia.trycloudflare.com/auth/callback",
  "https://blocked-makers-nathan-croatia.trycloudflare.com/auth/shopify/callback",
  "https://blocked-makers-nathan-croatia.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
