# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24a11b9ce5d2e9d267cc8d2943596106"
name = "remix-polaris"
handle = "remix-polaris-1"
application_url = "https://efficiently-copy-chris-soldiers.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://efficiently-copy-chris-soldiers.trycloudflare.com/auth/callback",
  "https://efficiently-copy-chris-soldiers.trycloudflare.com/auth/shopify/callback",
  "https://efficiently-copy-chris-soldiers.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
