# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "38dc56c47bcb390570d9b44bfbb52417"
name = "Customer-Loyalty-Review-App\r"
handle = "customer-loyalty-review-app"
application_url = "https://mills-su-finishing-load.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,write_products,write_fulfillments,write_discounts"

[auth]
redirect_urls = [
  "https://mills-su-finishing-load.trycloudflare.com/auth/callback",
  "https://mills-su-finishing-load.trycloudflare.com/auth/shopify/callback",
  "https://mills-su-finishing-load.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
